// AI GENERATED BY CLAUDE.AI - MOCK DATA FOR SCRIMBLE APP

export const COLORS = {
  bg: '#0D0B14',
  bgCard: '#1A1528',
  bgCardAlt: '#221C35',
  purple: '#7B3FE4',
  purpleLight: '#9B6FF0',
  purpleDark: '#4A1FA8',
  purpleMuted: '#2E1F5E',
  white: '#FFFFFF',
  grey: '#8A84A0',
  greyLight: '#C4BEDB',
  green: '#3DDB84',
  border: '#2A2244',
};

export const MOCK_POSTS = [
  {
    id: '1',
    username: 'VoidSniper_GG',
    avatar: null,
    game: 'Valorant',
    content: 'Looking for 2 more for ranked grind tonight. Plat+ only, need a duelist and a support. DM if interested 🎮',
    likes: 14,
    comments: 6,
    timestamp: '2h ago',
  },
  {
    id: '2',
    username: 'AishaFPS',
    avatar: null,
    game: 'CS2',
    content: 'Team Aether looking for a dedicated IGL for our weekly scrims. We run Tuesday/Thursday evenings. Competitive mindset essential.',
    likes: 22,
    comments: 11,
    timestamp: '5h ago',
  },
  {
    id: '3',
    username: 'RocketKing99',
    avatar: null,
    game: 'Rocket League',
    content: 'Anyone down for some casual 3v3 before the weekend tournament? Just warming up, all ranks welcome.',
    likes: 9,
    comments: 3,
    timestamp: '1d ago',
  },
];

export const MOCK_SCRIMS = [
  {
    id: 's1',
    name: 'Monday Ranked Scrim',
    teamA: 'Team Aether',
    teamB: 'NullPointer',
    game: 'Valorant',
    date: 'Mon 9 Jun, 8PM',
    status: 'upcoming',
  },
  {
    id: 's2',
    name: 'Practice Block',
    teamA: 'Solo Stack',
    teamB: 'Open',
    game: 'CS2',
    date: 'Wed 11 Jun, 7PM',
    status: 'open',
  },
];

export const MOCK_EVENTS = [
  {
    id: 'e1',
    name: 'NSE Spring Cup 2026',
    game: 'Valorant',
    date: '14–16 Jun',
    players: 32,
    type: 'tournament',
    community: 'ESL Esports',
    description: 'A competitive tournament featuring the best amateur Valorant teams across Europe. Best-of-3 matches in a double elimination bracket.',
    attending: 5,
  },
  {
    id: 'e2',
    name: 'UK Amateur Rocket League Open',
    game: 'Rocket League',
    date: '22 Jun',
    players: 16,
    type: 'tournament',
    community: 'RLCS Community',
    description: 'Join us for an exciting amateur Rocket League tournament. All skill levels welcome. Win prizes and bragging rights!',
    attending: 3,
  },
];

export const MOCK_EXPLORE = [
  {
    id: 'x1',
    type: 'tournament',
    name: 'NSE Spring Cup 2026',
    game: 'Valorant',
    date: '14–16 Jun 2026',
    players: 32,
    description: 'National Student Esports spring invitational. Open to all UK university teams.',
  },
  {
    id: 'x2',
    type: 'tournament',
    name: 'UK Amateur RL Open',
    game: 'Rocket League',
    date: '22 Jun 2026',
    players: 16,
    description: 'Online bracket for amateur Rocket League players. All ranks welcome.',
  },
  {
    id: 'x3',
    type: 'player',
    name: 'VoidSniper_GG',
    game: 'Valorant',
    description: 'Diamond Jett main. LFT for competitive roster. Available weekday evenings.',
    players: 1,
  },
  {
    id: 'x4',
    type: 'tournament',
    name: 'GG Clash Series #4',
    game: 'CS2',
    date: '29 Jun 2026',
    players: 24,
    description: 'Monthly amateur CS2 clash. Register your team by 25 Jun.',
  },
  {
    id: 'x5',
    type: 'player',
    name: 'AishaFPS',
    game: 'CS2',
    description: 'Team captain looking for an IGL. Running scrims Tue/Thu. Message to apply.',
    players: 4,
  },
];

export const MOCK_SQUAD = [
  { id: 'q1', username: 'pro', fullname: 'ProPlayer1', active: true },
  { id: 'q2', username: 'J4ke', fullname: 'Jake_OW', active: false },
  { id: 'q3', username: 'Null', fullname: 'NullPtr', active: true },
  { id: 'q4', username: 'Rei', fullname: 'ReiZone', active: false },
];

export const MOCK_MESSAGES = [
  {
    id: 'm1',
    username: 'AishaFPS',
    preview: 'Are you free for scrims this Thursday evening?',
    timestamp: '10m ago',
    unread: true,
  },
  {
    id: 'm2',
    username: 'VoidSniper_GG',
    preview: 'GG last night, that final round was insane 🔥',
    timestamp: '3h ago',
    unread: false,
  },
  {
    id: 'm3',
    username: 'RocketKing99',
    preview: 'Tournament bracket just dropped, we\'re vs NullPointer first',
    timestamp: '1d ago',
    unread: false,
  },
];

export const MOCK_COMMUNITIES = [
  { id: 'c1', name: 'Team Aether', members: 6, tag: 'CS2' },
  { id: 'c2', name: 'NSE Discord', members: 240, tag: 'Multi' },
];

export const MOCK_PROFILE = {
  username: 'YourUsername',
  bio: 'Amateur esports player. Valorant + CS2. Always down for scrims.',
  team: 'Team Aether',
  discord: 'user#1234',
  twitch: 'yourstream',
  stats: {
    rank: 'Diamond III',
    matches: 184,
    winRate: '61%',
    kd: '1.42',
  },
  achievements: [
    { id: 'a1', title: 'NSE Season 4 – Top 8', date: 'Apr 2026' },
    { id: 'a2', title: 'Rank Up: Diamond III', date: 'Mar 2026' },
    { id: 'a3', title: 'First Tournament Win', date: 'Jan 2026' },
  ],
};

export const GAME_INTEL = [
  {
    id: 'g1',
    title: 'Valorant Episode 9 Act 2 patch notes drop',
    source: 'Riot Games',
    time: '6h ago',
  },
  {
    id: 'g2',
    title: 'CS2 Premier season rankings reset incoming',
    source: 'HLTV',
    time: '1d ago',
  },
  {
    id: 'g3',
    title: 'NSE announces summer 2026 league dates',
    source: 'NSE',
    time: '2d ago',
  },
];
